version: '3'

services:

  gocron:
    build:
      context: .
    container_name: gocron
    image: chaiyd/gocron:1.5.3
    ports:
      - "5920:5920"
    volumes:
      - gocron-conf:/app/conf
      - gocron-log:/app/log
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
      MYSQL_DATABASE: gocorn
      MYSQL_USER: gocorn
      MYSQL_PASSWORD: ukC2ZkcG_ZTeb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  gocron-conf:
  gocron-log: