version: '3'

services:
    kafka:
        image: chaiyd/kafka:2.13-2.8.0
        environment:
            ZOOKEEPER_CONNECT: zookeeper:2181
            HOSTNAME: 192.168.0.1
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        restart: always
        volumes:
            - kafka:/tmp/kafka-logs

    zookeeper:
        image: zookeeper:3.6.2
        volumes:
            - zookeeper:/tmp
volumes:
    zookeeper:

