name: conda-python-3.7.5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CUDA_VER: '11.6.0-devel'
  CONDA_VER: '2021.11'
  PYTHON_VER: '3.7.5'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chaiyd/conda

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build and push Docker images & ubuntu18.04
        uses: docker/build-push-action@v2
        with:
          context: ./conda/ubuntu18.04
          file: ./conda/ubuntu18.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            CUDA_VER=${{ env.CUDA_VER }}
            CONDA_VER=${{ env.CONDA_VER }}
            PYTHON_VER=${{ env.PYTHON_VER }}
          tags: chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu18.04
          labels: chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu18.04

      - name: Build and push Docker images & ubuntu20.04
        uses: docker/build-push-action@v2
        with:
          context: ./conda/ubuntu20.04
          file: ./conda/ubuntu20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            CUDA_VER=${{ env.CUDA_VER }}
            CONDA_VER=${{ env.CONDA_VER }}
            PYTHON_VER=${{ env.PYTHON_VER }}
          tags: chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu20.04
          labels: chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu20.04

      - name: scan cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu18.04
        uses: anchore/scan-action@v3
        # id: scan
        with:
          image: |
            chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu18.04
          acs-report-enable: true
          fail-build: false

      - name: scan cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu20.04
        uses: anchore/scan-action@v3
        with:
          image: |
            chaiyd/conda:cuda${{ env.CUDA_VER }}-${{ env.PYTHON_VER }}-ubuntu20.04
          acs-report-enable: true
          fail-build: false

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          #sarif_file: ${{ steps.scan.outputs.sarif }}
          sarif_file: results.sarif
