name: Publish Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chaiyd/conda

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./conda
          file: ./conda/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: chaiyd/conda:cuda11.4.2-cudnn8-devel-ubuntu18.04
          labels: chaiyd/conda:cuda11.4.2-cudnn8-devel-ubuntu18.04

