name: yearning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BASEIMAGES: '3.15' 
  YEARNING_VER: '3.0.0-rc10'
  YEARNING_URL: 'https://github.com/cookieY/Yearning/releases/download/v3.0.0-rc10/Yearning-RC10.zip'
  
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chaiyd/yearning

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./yearning/
          file: ./yearning/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            BASEIMAGES=${{ env.BASEIMAGES }}
            YEARNING_VER=${{ env.YEARNING_VER }}
            YEARNING_URL=${{ env.YEARNING_URL }}

          tags: chaiyd/yearning:${{ env.YEARNING_VER }}
          labels: chaiyd/yearning:${{ env.YEARNING_VER }} 

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: |
            chaiyd/yearning:${{ env.YEARNING_VER }}
          acs-report-enable: true
          fail-build: false

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}            
